version: 1.0.{build}

branches:
  only:
    - master

assembly_info:
  patch: true
  file: AssemblyInfo.*
  assembly_version: "{version}"
  assembly_file_version: "{version}"
  assembly_informational_version: "{version}"

configuration: Release

build:
  project: Stone.Prepay.ApiClient.sln
  
after_test:
  - ps: .\Tools\pack.ps1

artifacts:
  - path: Stone.Prepay.ApiClient\bin\Release\Stone.Prepay.ApiClient.dll
    name: Stone.Prepay.ApiClient.dll
  - path: Stone.Prepay.ApiClient.*.nupkg

deploy:
    provider: NuGet
    server: http://mpnugetserver.cloudapp.net
    api_key:
        secure: XBpvvuiIUN5D3lMvB+k1FapXAtc4PR9OY1AV1B4v+aY=